CREATE TABLE IF NOT EXISTS downloads (id INTEGER PRIMARY KEY, date INTEGER NOT NULL, Link TEXT NOT NULL, Title TEXT, Author TEXT)
CREATE TABLE IF NOT EXISTS albums (id INTEGER PRIMARY  KEY, date INTEGER NOT NULL , Link TEXT, Title TEXT, Author TEXT)
