CREATE TABLE IF NOT EXISTS downloads (id INTEGER PRIMARY KEY, date INTEGER NOT NULL, Link TEXT NOT NULL, Title TEXT, Author TEXT, album_id INTEGER, FOREIGN KEY(album_id) REFERENCES allbums(id))
CREATE TABLE IF NOT EXISTS albums (id INTEGER PRIMARY  KEY, date INTEGER NOT NULL , Link TEXT, Title TEXT, Author TEXT, Length INTEGER)
